// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: heartbeat.proto

#include "heartbeat.pb.h"
#include "heartbeat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace heartbeat {

static const char* HeartbeatAPI_method_names[] = {
  "/heartbeat.HeartbeatAPI/Send",
};

std::unique_ptr< HeartbeatAPI::Stub> HeartbeatAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HeartbeatAPI::Stub> stub(new HeartbeatAPI::Stub(channel, options));
  return stub;
}

HeartbeatAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Send_(HeartbeatAPI_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HeartbeatAPI::Stub::Send(::grpc::ClientContext* context, const ::heartbeat::Beat& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::heartbeat::Beat, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Send_, context, request, response);
}

void HeartbeatAPI::Stub::async::Send(::grpc::ClientContext* context, const ::heartbeat::Beat* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::heartbeat::Beat, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void HeartbeatAPI::Stub::async::Send(::grpc::ClientContext* context, const ::heartbeat::Beat* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* HeartbeatAPI::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::heartbeat::Beat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::heartbeat::Beat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Send_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* HeartbeatAPI::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::heartbeat::Beat& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

HeartbeatAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HeartbeatAPI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HeartbeatAPI::Service, ::heartbeat::Beat, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HeartbeatAPI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::heartbeat::Beat* req,
             ::google::protobuf::Empty* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
}

HeartbeatAPI::Service::~Service() {
}

::grpc::Status HeartbeatAPI::Service::Send(::grpc::ServerContext* context, const ::heartbeat::Beat* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace heartbeat

